Module 1 Capstone Project for code review.
demix007/Capstone1-Project-Style-Conference pull request #1
Opened 2022-09-23 11:38 UTC by demix007

# In the process of building this capstone project, I did the following:
- Set up the Linters and ensured that there are no linter errors. 
- Used the correct GitHub flow.
- Used the recommended design guidelines including colors, typography, and layout.
- Built the first two pages: The home page and the about page.
- Ensured that each page has versions for 2 different sizes: the mobile (up to 768px wide) and the desktop(768px or wider) versions.
- Created interactions on the site (Links and mobile menu).
- Created the section "Featured Speakers" dynamically in JavaScript.

2022-09-23 15:38 UTC, fobadara requested changes
Hi @demix007, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can improve your code._

You can also consider:

- [OPTIONAL] Good job  👍🏽  following some of the best practices for writing commit messages but I think your commit message for a project as large as this should be more.

- [OPTIONAL] I don't think you need to include `-branch` in the title of your feature branch. we also know you include features in this branch but I think we can use a more specific name for projects like this. Perhaps `full_project`. You can check out how to change a branch name  [here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)

- [OPTIONAL] I also noticed that the name of your repo doesn't tell us much at first glance. You are going to have a lot of capstone projects. And imagine getting a job and naming the repo job. I think something like lighthouse-2022 might have been better. Kindly treat these projects like you are working a real job.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-23 15:38 UTC, fobadara commented on README.md
> +[Live Demo Link](https://www.loom.com/share/afa22ca17b604af38c8cc5b72b1f09f9)
- [x] [REQUIRED] There is something wrong with your video. It is not playing despite trying it on about 3 browsers.
- [OPTIONAL] I think you should have named this something like `video` or `video presentation`

2022-09-23 15:38 UTC, fobadara commented on README.md
- [x] [REQUIRED] Kindly give us details on how we can use your website.

2022-09-23 15:38 UTC, fobadara commented on README.md
> +- Created the section "Featured Speakers" dynamically in JavaScript.
[OPTIONAL] I think this sounds. more like a PR summary than an intro.  This space is for you to tell us about what your site does and what makes it special.

2022-09-23 15:38 UTC, fobadara commented on README.md
- [x] [REQUIRED] Kindly credit Cindy (the owner of the design on Behance) in your acknowledgements section of your README as instructed. And don't forget to include a link.

2022-09-23 15:38 UTC, fobadara commented on about.html
> +                  <a href="index.html">Home</a>
- [x] [REQUIRED] For some reason your `home` button is not showing on the about page. Kindly fix this.

2022-09-23 15:38 UTC, fobadara commented on about.html
> +            </nav>
- [x] [REQUIRED] Kindly fix your hamburger button for the about page. It doesn't display the popup navigation when it is clicked.
- [x] [REQUIRED] Kindly make your navigation pop up transparent

2022-09-23 15:38 UTC, fobadara commented on index.html
> +                            <a href="about.html" class="active-tab">About</a>
- [OPTIONAL] I think you should make only the current page orange colour

2022-09-23 15:38 UTC, fobadara commented on index.html
> +        </div>
- [x] [REQUIRED] Kindly make sure the corrections pointed out matches Cindy's design. One of the purposes of this task is to teach to follow client requirements.

| Your Design|
|-------------|
|![image](https://user-images.githubusercontent.com/62938735/191987820-1203ffcb-11e2-4034-982d-f841b3b2ffd9.png)|

2022-09-23 15:38 UTC, fobadara commented on index.html
> +                    <img src="img/game5.png" alt="event-icon" class="event-img event-icon">
- [x] [REQUIRED] Kindly take note of the differences between your design and. Cindy's in the image below:

|Your Design|
|-------------|
|![image](https://user-images.githubusercontent.com/62938735/191990299-ccd115d4-1df8-48b6-bf26-d63bad5523fe.png)|

2022-09-23 15:38 UTC, fobadara commented on index.html
> +
- [ ] [REQUIRED]  kindly check the image below:

|Your Design|
|----------|
|![image](https://user-images.githubusercontent.com/62938735/191991202-b21c12bd-7fde-4c61-9fb6-fa46d9208afe.png)|

- [ ] [REQUIRED] Kindly reduce the width and  make the speakers in the centre for the mobile version

2022-09-24 03:51 UTC, danielufeli requested changes
Hi @demix007 , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Design ✔️

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-24 03:51 UTC, danielufeli commented on README.md
> +[Project Description Video](https://www.loom.com/share/afa22ca17b604af38c8cc5b72b1f09f9)
- [ ] Nice working on your video presentation, like the previous reviewer mentioned the video is not loading, kindly fix this.

2022-09-24 17:58 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @demix007 :wave:

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

:heavy_check_mark: Following the GitHub Flow
:heavy_check_mark: Descriptive PR Summary
:heavy_check_mark: Descriptive PR Title
✔️ Following the Requirements

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 18:03 UTC, merged

2023-01-09 15:21 UTC, demix007 commented on README.md
> +[Live Demo Link](https://www.loom.com/share/afa22ca17b604af38c8cc5b72b1f09f9)
## Hello @fobadara 👋🏼,

Thank you for reviewing, the changes which you required have been implemented.

2023-01-09 15:22 UTC, demix007 commented on README.md
> +- Created the section "Featured Speakers" dynamically in JavaScript.
I have also implemented this change.

2023-01-09 15:23 UTC, demix007 commented
## Hello @HAMMAS-SALEEM 👋🏼 ,

Thank you for taking out time to review and approve this PR. You are amazing 💯